"""
Shark Vision Mode

Most sharks are believed to be monochromats or, at best, dichromats with
only a single long-wavelength cone type.  Great white sharks lack S-cones
entirely and perceive the world primarily in grey-blue tones.

Additional sensory note — electroreception:
Sharks possess the Ampullae of Lorenzini: jelly-filled pores that detect
the weak electric fields (as small as 5 nV/m) generated by muscle
contractions and heartbeats in nearby fish.  This is simulated as a
low-frequency electrical interference shimmer overlaid on the frame.

Key visual characteristics:
- High contrast sensitivity (rod-dominated retina)
- Blue-dominant monochromatic colour perception
- Superior motion detection
- Low-frequency electrical shimmer (electroreception proxy)
"""

import numpy as np
import cv2
from modes.base_mode import BaseVisionMode
from effects.color_filters import apply_channel_weights, adjust_saturation
from effects.contrast import gamma_correction, clahe_enhance


class SharkVision(BaseVisionMode):
    """
    Simulates shark visual + electroreception perception.
    """

    def __init__(self) -> None:
        self._frame_count: int = 0

    @property
    def name(self) -> str:
        return "Shark Vision"

    @property
    def description(self) -> str:
        return "Blue-grey monochromatic vision with electroreception shimmer."

    def apply(self, frame: np.ndarray) -> np.ndarray:
        """
        Applies shark perception simulation.

        Steps:
        1. Heavy blue dominance, near-zero red (single L-cone type).
        2. Low-light adaptation via gamma < 1.0 (rod-dominated retina).
        3. CLAHE for high motion/contrast sensitivity.
        4. Strong desaturation (monochromatic cone sensitivity).
        5. Electroreception shimmer overlay.

        Args:
            frame: Raw BGR screen capture.

        Returns:
            Processed BGR frame with shark visual characteristics.
        """
        # Sharks have very limited red sensitivity; strong blue response
        blue_dominant = apply_channel_weights(frame, b=1.6, g=0.85, r=0.25)

        # Rod-dominated → performs well in dim, turbid ocean water
        adapted = gamma_correction(blue_dominant, gamma=0.75)

        # High contrast/motion sensitivity
        contrasted = clahe_enhance(adapted, clip_limit=3.5, tile_size=8)

        # Monochromatic (or near-monochromatic) colour perception
        desaturated = adjust_saturation(contrasted, factor=0.35)

        # Overlay the electroreception shimmer
        return self._electroreception_overlay(desaturated)

    def _electroreception_overlay(self, frame: np.ndarray) -> np.ndarray:
        """
        Adds a low-frequency interference shimmer to simulate electroreception.

        Sharks detect electric fields as spatial patterns of slight
        brightness variation.  This is approximated by overlaying smooth,
        slowly varying noise on the blue channel.

        Args:
            frame: BGR image array.

        Returns:
            Frame with electroreception shimmer.
        """
        self._frame_count += 1
        h, w = frame.shape[:2]

        # Generate smooth low-frequency noise (8× down-sampled → blurred)
        noise_small = np.random.randint(-18, 19, (h // 8, w // 8), dtype=np.int16)
        noise = cv2.resize(
            noise_small.astype(np.float32), (w, h), interpolation=cv2.INTER_LINEAR
        )
        # Apply only to the blue channel (sharks sense EM fields → blue haze)
        result = frame.astype(np.float32)
        result[:, :, 0] = np.clip(result[:, :, 0] + noise * 0.8, 0, 255)
        return result.astype(np.uint8)
